### ISSUE TITLE
ImportError: cannot import name 'ChangeLane' from 'hybrid_simulation.msg' (unknown location)

### ISSUE THREAD

**Issue by VladMarianCimpeanu** [marioney/hybrid_simulation#6]
Hi Mario,
I am trying to use your plugin and first I wanted to try hybrid simulation demo, but once I launch the command
`roslaunch hybrid_simulation hybrid_simulation.launch` 
I get the following error:

```
Traceback (most recent call last):
  File "/home/vlad/Desktop/hybrid_simulation_ws/src/hybrid_simulation/scripts/control_other_vehicles.py", line 37, in <module>
    from hybrid_simulation.ego_vehicle import EgoVehicle
  File "/home/vlad/Desktop/hybrid_simulation_ws/src/hybrid_simulation/src/hybrid_simulation/ego_vehicle.py", line 4, in <module>
    from hybrid_simulation.msg import ChangeLane
ImportError: cannot import name 'ChangeLane' from 'hybrid_simulation.msg' (unknown location)
```
If it is more helpful here you can find the entire output of hybrid_simulation.launch:

```
vlad@vlad-ThinkPad-E14:~/Desktop/hybrid_simulation_ws$ roslaunch hybrid_simulation hybrid_simulation.launch
... logging to /home/vlad/.ros/log/ef644dc8-d61b-11ed-aba5-b9b107674f38/roslaunch-vlad-ThinkPad-E14-31984.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://vlad-ThinkPad-E14:38911/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /sumo_interface/control_ego_vehicle: True
 * /sumo_interface/control_from_gazebo: False
 * /sumo_interface/ego_vehicle_name: prius
 * /sumo_interface/n_scenario: 6
 * /sumo_interface/route_file_name: network_traci.rou...
 * /sumo_interface/sumo_config_file_name: network.sumocfg
 * /sumo_interface/use_gazebo: True
 * /use_sim_time: True

NODES
  /
    ego_vehicle_state_publisher (robot_state_publisher/robot_state_publisher)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    prius_to_baselink (tf2_ros/static_transform_publisher)
    spawn_ego_vehicle_urdf (gazebo_ros/spawn_model)
    sumo_interface (hybrid_simulation/control_other_vehicles.py)

auto-starting new master
process[master]: started with pid [31992]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ef644dc8-d61b-11ed-aba5-b9b107674f38
process[rosout-1]: started with pid [32002]
started core service [/rosout]
process[gazebo-2]: started with pid [32009]
process[gazebo_gui-3]: started with pid [32014]
process[spawn_ego_vehicle_urdf-4]: started with pid [32019]
process[ego_vehicle_state_publisher-5]: started with pid [32020]
process[prius_to_baselink-6]: started with pid [32021]
process[sumo_interface-7]: started with pid [32022]
[ WARN] [1680965099.357939656]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
Traceback (most recent call last):
  File "/home/vlad/Desktop/hybrid_simulation_ws/src/hybrid_simulation/scripts/control_other_vehicles.py", line 37, in <module>
    from hybrid_simulation.ego_vehicle import EgoVehicle
  File "/home/vlad/Desktop/hybrid_simulation_ws/src/hybrid_simulation/src/hybrid_simulation/ego_vehicle.py", line 4, in <module>
    from hybrid_simulation.msg import ChangeLane
ImportError: cannot import name 'ChangeLane' from 'hybrid_simulation.msg' (unknown location)
[ INFO] [1680965099.834340541]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1680965099.835221096]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1680965099.943676601]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1680965099.944553415]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[sumo_interface-7] process has died [pid 32022, exit code 1, cmd /home/vlad/Desktop/hybrid_simulation_ws/src/hybrid_simulation/scripts/control_other_vehicles.py __name:=sumo_interface __log:=/home/vlad/.ros/log/ef644dc8-d61b-11ed-aba5-b9b107674f38/sumo_interface-7.log].
log file: /home/vlad/.ros/log/ef644dc8-d61b-11ed-aba5-b9b107674f38/sumo_interface-7*.log
[ INFO] [1680965100.536523494]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1680965100.558526930, 0.004000000]: Physics dynamic reconfigure ready.
[ INFO] [1680965101.503870694, 0.161000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1680965101.506424497, 0.161000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ WARN] [1680965101.558831363, 0.161000000]: Range plugin missing <radiation>, defaults to ultrasound
[ WARN] [1680965101.558869143, 0.161000000]: Range plugin missing <fov>, defaults to 0.05
[ INFO] [1680965101.558905883, 0.161000000]: Range plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1680965101.558956196, 0.161000000]: Range plugin missing <updateRate>, defaults to 0
[ WARN] [1680965101.562406998, 0.161000000]: Range plugin missing <radiation>, defaults to ultrasound
[ WARN] [1680965101.562444715, 0.161000000]: Range plugin missing <fov>, defaults to 0.05
[ INFO] [1680965101.562460160, 0.161000000]: Range plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1680965101.562479817, 0.161000000]: Range plugin missing <updateRate>, defaults to 0
[ WARN] [1680965101.562708869, 0.161000000]: Range plugin missing <radiation>, defaults to ultrasound
[ WARN] [1680965101.562735545, 0.161000000]: Range plugin missing <fov>, defaults to 0.05
[ INFO] [1680965101.562763464, 0.161000000]: Range plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1680965101.562780823, 0.161000000]: Range plugin missing <updateRate>, defaults to 0
[ WARN] [1680965101.562929814, 0.161000000]: Range plugin missing <radiation>, defaults to ultrasound
[ WARN] [1680965101.562965943, 0.161000000]: Range plugin missing <fov>, defaults to 0.05
[ INFO] [1680965101.562992102, 0.161000000]: Range plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1680965101.563018113, 0.161000000]: Range plugin missing <updateRate>, defaults to 0
[ INFO] [1680965103.650393100, 0.161000000]: Block laser plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1680965103.650533140, 0.161000000]: Block laser plugin missing <hokuyoMinIntensity>, defaults to 101
[ INFO] [1680965103.650587162, 0.161000000]: Block laser plugin missing <updateRate>, defaults to 0
[ INFO] [1680965103.663678473, 0.161000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ WARN] [1680965103.665183151, 0.161000000]: Range plugin missing <radiation>, defaults to ultrasound
[ WARN] [1680965103.665280672, 0.161000000]: Range plugin missing <fov>, defaults to 0.05
[ INFO] [1680965103.665308178, 0.161000000]: Range plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1680965103.665351760, 0.161000000]: Range plugin missing <updateRate>, defaults to 0
[ INFO] [1680965103.666463826, 0.161000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1680965103.868438705, 0.161000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1680965103.868537764, 0.161000000]: Starting Laser Plugin (ns = /)
[ INFO] [1680965103.869855914, 0.161000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ WARN] [1680965103.870048145, 0.161000000]: Range plugin missing <radiation>, defaults to ultrasound
[ WARN] [1680965103.870094102, 0.161000000]: Range plugin missing <fov>, defaults to 0.05
[ INFO] [1680965103.870142728, 0.161000000]: Range plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1680965103.870172144, 0.161000000]: Range plugin missing <updateRate>, defaults to 0
[ WARN] [1680965103.872692544, 0.161000000]: Range plugin missing <radiation>, defaults to ultrasound
[ WARN] [1680965103.872722500, 0.161000000]: Range plugin missing <fov>, defaults to 0.05
[ INFO] [1680965103.872735005, 0.161000000]: Range plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1680965103.872793737, 0.161000000]: Range plugin missing <updateRate>, defaults to 0
[ INFO] [1680965104.062412923, 0.161000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1680965104.062456123, 0.161000000]: Starting Laser Plugin (ns = /)
[ INFO] [1680965104.063345764, 0.161000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ WARN] [1680965104.064863454, 0.161000000]: Range plugin missing <radiation>, defaults to ultrasound
[ WARN] [1680965104.064900937, 0.161000000]: Range plugin missing <fov>, defaults to 0.05
[ INFO] [1680965104.064923569, 0.161000000]: Range plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1680965104.064944555, 0.161000000]: Range plugin missing <updateRate>, defaults to 0
[ INFO] [1680965104.077680822, 0.161000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1680965104.079649387, 0.161000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1680965104.088992232, 0.161000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1680965104.091384229, 0.161000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1680965104.101624652, 0.161000000]: GazeboRosJointStatePublisher is going to publish joint: rear_right_wheel_joint
[ INFO] [1680965104.101798001, 0.161000000]: GazeboRosJointStatePublisher is going to publish joint: rear_left_wheel_joint
[ INFO] [1680965104.102551167, 0.161000000]: GazeboRosJointStatePublisher is going to publish joint: front_right_wheel_joint
[ INFO] [1680965104.103375285, 0.161000000]: GazeboRosJointStatePublisher is going to publish joint: front_left_wheel_joint
[ INFO] [1680965104.103975282, 0.161000000]: GazeboRosJointStatePublisher is going to publish joint: front_right_steer_joint
[ INFO] [1680965104.104732590, 0.161000000]: GazeboRosJointStatePublisher is going to publish joint: front_left_steer_joint
[ INFO] [1680965104.105356127, 0.161000000]: GazeboRosJointStatePublisher is going to publish joint: steering_joint
[ INFO] [1680965104.106029353, 0.161000000]: Starting GazeboRosJointStatePublisher Plugin (ns = //)!, parent name: prius
[spawn_ego_vehicle_urdf-4] process has finished cleanly
log file: /home/vlad/.ros/log/ef644dc8-d61b-11ed-aba5-b9b107674f38/spawn_ego_vehicle_urdf-4*.log
[sumo_interface-7] restarting process
process[sumo_interface-7]: started with pid [32347]
Traceback (most recent call last):
  File "/home/vlad/Desktop/hybrid_simulation_ws/src/hybrid_simulation/scripts/control_other_vehicles.py", line 37, in <module>
    from hybrid_simulation.ego_vehicle import EgoVehicle
  File "/home/vlad/Desktop/hybrid_simulation_ws/src/hybrid_simulation/src/hybrid_simulation/ego_vehicle.py", line 4, in <module>
    from hybrid_simulation.msg import ChangeLane
ImportError: cannot import name 'ChangeLane' from 'hybrid_simulation.msg' (unknown location)
[sumo_interface-7] process has died [pid 32347, exit code 1, cmd /home/vlad/Desktop/hybrid_simulation_ws/src/hybrid_simulation/scripts/control_other_vehicles.py __name:=sumo_interface __log:=/home/vlad/.ros/log/ef644dc8-d61b-11ed-aba5-b9b107674f38/sumo_interface-7.log].
log file: /home/vlad/.ros/log/ef644dc8-d61b-11ed-aba5-b9b107674f38/sumo_interface-7*.log
^C[sumo_interface-7] killing on exit
[prius_to_baselink-6] killing on exit
[ego_vehicle_state_publisher-5] killing on exit
[gazebo_gui-3] killing on exit
[gazebo-2] killing on exit
[gazebo_gui-3] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```
Can you provide me any workaround?

**Comment by VladMarianCimpeanu** [comment]
I've just realized before running `catkin_make hybrid_simulation` I have to run `catkin_make` too. Now it works fine.
